s01 = School.create!(name: "PS131")

j01 = Janitor.create!(name: "Bob", school: s01)
j02 = Janitor.create!(name: "George", school: s01)

m01 = Mop.create!(brand: "KeepClean")
m02 = Mop.create!(brand: "KeepClean")
m03 = Mop.create!(brand: "KeepClean")

jm01 = Janitormop.create!(janitor:j01, mop:m01)
jm02 = Janitormop.create!(janitor:j02, mop:m02)

f01 = Floor.create!(flr: "1st", shininess: 8)
f02 = Floor.create!(flr: "2nd", shininess: 6)
f03 = Floor.create!(flr: "3rd", shininess: 10)
f04 = Floor.create!(flr: "4th", shininess: 3)
f05 = Floor.create!(flr: "5th", shininess: 9)
f06 = Floor.create!(flr: "6th", shininess: 4)
f07 = Floor.create!(flr: "7th", shininess: 8)
f08 = Floor.create!(flr: "8th", shininess: 10)
f09 = Floor.create!(flr: "9th", shininess: 10)

mf01 = Mopfloor.create!(mop: m01, floor: f01)
mf02 = Mopfloor.create!(mop: m01, floor: f02)
mf03 = Mopfloor.create!(mop: m02, floor: f03)
mf04 = Mopfloor.create!(mop: m02, floor: f04)
mf05 = Mopfloor.create!(mop: m01, floor: f05)
mf06 = Mopfloor.create!(mop: m01, floor: f06)
mf07 = Mopfloor.create!(mop: m02, floor: f07)
mf08 = Mopfloor.create!(mop: m02, floor: f08)
mf09 = Mopfloor.create!(mop: m02, floor: f09)

t01 = Teacher.create!(name: "Ms.Mcgonagall", school: s01)
t02 = Teacher.create!(name: "Mr.Lupin", school: s01)

sd01 = Student.create!(name: "Jim", school: s01)
sd02 = Student.create!(name: "Emily", school: s01)
sd03 = Student.create!(name: "Zack", school: s01)
sd04 = Student.create!(name: "Ashley", school: s01)

sj01 = Subject.create!(name: "English")
sj02 = Subject.create!(name: "Math")
sj03 = Subject.create!(name: "Science")
sj04 = Subject.create!(name: "Social Studies")

ss01 = Studentsubject.create!(student: sd01, subject: sj01)
ss02 = Studentsubject.create!(student: sd01, subject: sj02)
ss03 = Studentsubject.create!(student: sd01, subject: sj03)
ss04 = Studentsubject.create!(student: sd01, subject: sj04)
ss05 = Studentsubject.create!(student: sd02, subject: sj01)
ss06 = Studentsubject.create!(student: sd02, subject: sj02)
ss07 = Studentsubject.create!(student: sd02, subject: sj03)
ss08 = Studentsubject.create!(student: sd02, subject: sj04)
ss09 = Studentsubject.create!(student: sd03, subject: sj01)
ss10 = Studentsubject.create!(student: sd03, subject: sj02)
ss11 = Studentsubject.create!(student: sd03, subject: sj03)
ss12 = Studentsubject.create!(student: sd03, subject: sj04)
ss13 = Studentsubject.create!(student: sd04, subject: sj01)
ss14 = Studentsubject.create!(student: sd04, subject: sj02)
ss15 = Studentsubject.create!(student: sd04, subject: sj03)
ss16 = Studentsubject.create!(student: sd04, subject: sj04)
